import json, os, copy

PROJECTS_JSON = r"d:\Geonixa Platform\frontend\public\data\projects.json"

# Realistic Java file templates keyed by filename suffix / role
def make_main_java(title):
    cls = ''.join(w.capitalize() for w in title.split()[:3])
    return f"""package com.geonixa.{cls.lower()};

import java.util.Scanner;

/**
 * Main entry point for {title}
 * @version 1.0
 */
public class Main {{

    public static void main(String[] args) {{
        System.out.println("Starting {title}...");
        {cls}App app = new {cls}App();
        app.initialize();
        app.run();
    }}
}}
"""

def make_model_java(title):
    cls = ''.join(w.capitalize() for w in title.split()[:2]) + "Model"
    return f"""package com.geonixa.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Data model for {title}
 */
public class {cls} implements Serializable {{

    private static final long serialVersionUID = 1L;

    private int id;
    private String name;
    private String description;
    private Date createdAt;
    private boolean isActive;

    public {cls}() {{
        this.createdAt = new Date();
        this.isActive = true;
    }}

    public {cls}(int id, String name, String description) {{
        this.id = id;
        this.name = name;
        this.description = description;
        this.createdAt = new Date();
        this.isActive = true;
    }}

    // Getters and Setters
    public int getId() {{ return id; }}
    public void setId(int id) {{ this.id = id; }}

    public String getName() {{ return name; }}
    public void setName(String name) {{ this.name = name; }}

    public String getDescription() {{ return description; }}
    public void setDescription(String description) {{ this.description = description; }}

    public Date getCreatedAt() {{ return createdAt; }}
    public boolean isActive() {{ return isActive; }}
    public void setActive(boolean active) {{ isActive = active; }}

    @Override
    public String toString() {{
        return "{cls}{{id=" + id + ", name='" + name + "', active=" + isActive + "}}";
    }}
}}
"""

def make_dao_java(title):
    cls = ''.join(w.capitalize() for w in title.split()[:2]) + "DAO"
    return f"""package com.geonixa.dao;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Data Access Object for {title}
 */
public class {cls} {{

    private static final String URL = "jdbc:mysql://localhost:3306/geonixa_db";
    private static final String USER = "root";
    private static final String PASS = "";

    private Connection getConnection() throws SQLException {{
        return DriverManager.getConnection(URL, USER, PASS);
    }}

    public boolean insert(String name, String description) {{
        String sql = "INSERT INTO records (name, description, created_at) VALUES (?, ?, NOW())";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {{
            stmt.setString(1, name);
            stmt.setString(2, description);
            return stmt.executeUpdate() > 0;
        }} catch (SQLException e) {{
            System.err.println("Insert error: " + e.getMessage());
            return false;
        }}
    }}

    public List<String[]> findAll() {{
        List<String[]> results = new ArrayList<>();
        String sql = "SELECT id, name, description FROM records ORDER BY id";
        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {{
            while (rs.next()) {{
                results.add(new String[]{{
                    String.valueOf(rs.getInt("id")),
                    rs.getString("name"),
                    rs.getString("description")
                }});
            }}
        }} catch (SQLException e) {{
            System.err.println("Query error: " + e.getMessage());
        }}
        return results;
    }}

    public boolean deleteById(int id) {{
        String sql = "DELETE FROM records WHERE id = ?";
        try (Connection conn = getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {{
            stmt.setInt(1, id);
            return stmt.executeUpdate() > 0;
        }} catch (SQLException e) {{
            System.err.println("Delete error: " + e.getMessage());
            return false;
        }}
    }}
}}
"""

def make_schema_sql(title):
    return f"""-- Database Schema for {title}
-- Generated by Geonixa Platform

CREATE DATABASE IF NOT EXISTS geonixa_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE geonixa_db;

-- Records table
CREATE TABLE IF NOT EXISTS records (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    status      ENUM('active','inactive','pending') DEFAULT 'active',
    created_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_status (status),
    INDEX idx_created (created_at)
) ENGINE=InnoDB;

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    username     VARCHAR(100) UNIQUE NOT NULL,
    email        VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role         ENUM('admin','user','guest') DEFAULT 'user',
    is_active    TINYINT(1) DEFAULT 1,
    last_login   DATETIME,
    created_at   DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Audit log
CREATE TABLE IF NOT EXISTS audit_log (
    id         INT AUTO_INCREMENT PRIMARY KEY,
    user_id    INT,
    action     VARCHAR(100) NOT NULL,
    entity     VARCHAR(100),
    entity_id  INT,
    logged_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Sample data
INSERT INTO users (username, email, password_hash, role) VALUES
('admin', 'admin@geonixa.com', SHA2('admin123', 256), 'admin'),
('student1', 'student1@example.com', SHA2('pass123', 256), 'user');
"""

def make_pom_xml(title):
    art = title.lower().replace(' ', '-')[:30]
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.geonixa</groupId>
  <artifactId>{art}</artifactId>
  <version>1.0.0</version>
  <packaging>jar</packaging>

  <name>{title}</name>
  <description>Engineering project: {title}</description>
  <url>https://github.com/Geonixa/{art}</url>

  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <!-- MySQL JDBC Driver -->
    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
      <version>8.0.33</version>
    </dependency>

    <!-- JUnit for testing -->
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.2</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.3.0</version>
        <configuration>
          <archive>
            <manifest>
              <mainClass>com.geonixa.Main</mainClass>
            </manifest>
          </archive>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
"""

def make_readme(title, desc, stack):
    stack_str = ', '.join(stack) if stack else 'Java'
    return f"""# {title}

> {desc}

## Technologies Used
{chr(10).join(f'- {t}' for t in stack)}

## Prerequisites
- Java 17 or higher
- Maven 3.8+
- MySQL 8.0+
- IDE: IntelliJ IDEA / Eclipse

## Project Structure
```
{title}/
├── src/
│   ├── Main.java
│   ├── model/
│   │   └── Model.java
│   └── dao/
│       └── DAO.java
├── database/
│   └── schema.sql
├── pom.xml
└── README.md
```

## Getting Started

### 1. Clone the Repository
```bash
git clone https://github.com/Geonixa/{title.lower().replace(' ', '-')}.git
cd {title.lower().replace(' ', '-')}
```

### 2. Set Up the Database
```bash
mysql -u root -p < database/schema.sql
```

### 3. Configure Database Connection
Edit `src/dao/DAO.java` and update:
```java
private static final String URL  = "jdbc:mysql://localhost:3306/geonixa_db";
private static final String USER = "your_username";
private static final String PASS = "your_password";
```

### 4. Build & Run
```bash
mvn clean package
java -jar target/*.jar
```

## Features
- Complete CRUD operations
- MySQL database integration
- Clean MVC architecture
- Maven build system

## License
This project is for educational purposes by Geonixa Platform.
"""

def make_service_java(title):
    cls = ''.join(w.capitalize() for w in title.split()[:2]) + "Service"
    return f"""package com.geonixa.service;

import com.geonixa.dao.*;
import java.util.List;

/**
 * Business logic service layer for {title}
 */
public class {cls} {{

    private final Object dao;

    public {cls}() {{
        this.dao = new Object(); // Replace with actual DAO
    }}

    /**
     * Validates and processes new entry
     */
    public boolean processNew(String name, String description) {{
        if (name == null || name.trim().isEmpty()) {{
            throw new IllegalArgumentException("Name cannot be empty");
        }}
        if (description == null || description.trim().isEmpty()) {{
            throw new IllegalArgumentException("Description cannot be empty");
        }}
        System.out.println("[{cls}] Processing: " + name);
        return true;
    }}

    /**
     * Retrieves all records
     */
    public void fetchAll() {{
        System.out.println("[{cls}] Fetching all records...");
    }}

    /**
     * Removes a record by ID
     */
    public boolean remove(int id) {{
        if (id <= 0) throw new IllegalArgumentException("Invalid ID: " + id);
        System.out.println("[{cls}] Removing record: " + id);
        return true;
    }}
}}
"""

def build_source_files(title, desc, stack):
    return [
        {"path": "src/Main.java",                 "name": "Main.java",      "content": make_main_java(title)},
        {"path": "src/model/Model.java",           "name": "Model.java",     "content": make_model_java(title)},
        {"path": "src/dao/DAO.java",               "name": "DAO.java",       "content": make_dao_java(title)},
        {"path": "src/service/Service.java",       "name": "Service.java",   "content": make_service_java(title)},
        {"path": "database/schema.sql",            "name": "schema.sql",     "content": make_schema_sql(title)},
        {"path": "pom.xml",                        "name": "pom.xml",        "content": make_pom_xml(title)},
        {"path": "README.md",                      "name": "README.md",      "content": make_readme(title, desc, stack)},
    ]

def is_java_project(p):
    return (
        p.get('category') == 'Java Projects' or
        any(t.lower() == 'java' for t in p.get('technologyStack', []))
    )

with open(PROJECTS_JSON, 'r', encoding='utf-8') as f:
    projects = json.load(f)

updated = 0
for p in projects:
    if is_java_project(p):
        p['sourceFiles'] = build_source_files(
            p.get('title', 'Project'),
            p.get('shortDescription', ''),
            p.get('technologyStack', [])
        )
        updated += 1

with open(PROJECTS_JSON, 'w', encoding='utf-8') as f:
    json.dump(projects, f, indent=2, ensure_ascii=False)

print(f"Done. Updated sourceFiles for {updated} Java projects.")
